// Generated by CoffeeScript 1.8.0
(function() {
  var arr, val, _i, _len;

  arr = ["a", "b", "c", "d", "e"];

  for (_i = 0, _len = arr.length; _i < _len; _i++) {
    val = arr[_i];
    console.log(val);
  }

}).call(this);
